apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-pdx1
  namespace: argocd
  labels:
    cluster: pdx1
    component: observability
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: tempo
    helm:
      valueFiles:
        - environments/pdx1-monitoring-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
