apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdx1-metallb-config
  namespace: argocd
  labels:
    cluster: pdx1
    component: metallb
    type: infrastructure
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: networking/pdx1/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
