apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noctel-worker-indexer-prod
  namespace: argocd
  labels:
    environment: prod
    component: noctel-worker-indexer
spec:
  project: noctel-prod
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: noctel-worker-indexer/charts
    helm:
      valueFiles:
        - ../environments/pdx1-prod-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
