apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.global.namespace | default "default" }}
type: Opaque
stringData:
  {{- with index .Values "noctel-display" "env" }}
  {{- if hasKey . "JWT_ACCESS_SECRET" }}
  JWT_ACCESS_SECRET: {{ .JWT_ACCESS_SECRET | quote }}
  {{- end }}
  {{- if hasKey . "SESSION_SECRET" }}
  SESSION_SECRET: {{ .SESSION_SECRET | quote }}
  {{- end }}
  {{- end }}