apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdx1-management-networking
  namespace: argocd
  labels:
    environment: management
    component: networking
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: networking/pdx1/management
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
