global:
  namespace: default

noctel-api-realtime:
  replicaCount: 1
  version: "latest"
  image:
    pullPolicy: IfNotPresent
  securityContext:
    fsGroup: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    runAsUser: 1001
