global:
  cluster: pdx1
  namespace: qa
  domain: { prefix: pdx1-qa, base: telnoc.com }

noctel-worker-file:
  version: "latest"
  replicaCount: 2
  image:
    repository: pdx-harbor.telnoc.com/noctel/noctel-api-file-worker
    pullPolicy: Always
  env:
    HEALTH_PORT: "9275"
    HOST: "0.0.0.0"
    SERVICE_NAME: file-worker
    LOG_LEVEL: info
    NODE_ENV: qa
  resources:
    requests: { cpu: 100m, memory: 192Mi }
    limits:   { cpu: "1", memory: 768Mi }
