global:
  cluster: pdx1
  namespace: qa
  environment: qa
  domain:
    prefix: pdx1-qa
    base: telnoc.com

noctel-api-billing:
  version: "latest"
  replicaCount: 3
  image:
    pullPolicy: Always
  env:
    SERVICE_NAME: billing
  secrets:
