apiVersion: v2
name: noctel-api-e911
description: noctel-api-e911 - Emergency Services (E911) location and routing service
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: NocTel Team
    email: tech@noctel.com
