apiVersion: v2
name: noctel-api-super
description: noctel-api-super - Admin and super user management service
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: NocTel Team
    email: tech@noctel.com
