apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3001
    protocol: TCP
    name: basic-station-ws
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: basic-station-wss
  selector:
    app: {{ .Chart.Name }}
