apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-pdx2
  namespace: argocd
  labels:
    cluster: pdx2
    component: monitoring
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: manifests/kube-prometheus-stack
    helm:
      valueFiles:
        - ../../environments/pdx2/pdx2-monitoring-config.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
