apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-http01
  namespace: qa
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: noc@telnoc.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: traefik-qa
