global:
  namespace: prod
  imagePullSecrets:
    - name: harbor-pull
    - name: dockerhub-secret

noctel-worker-carriers:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
