apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noctel-clickhouse-migrations-prod-pdx2
  namespace: argocd
  labels:
    environment: prod
    cluster: pdx2
    component: noctel-clickhouse-migrations
spec:
  project: noctel-prod
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: noctel-clickhouse-migrations/charts
    helm:
      valueFiles:
        - ../environments/pdx2-prod-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
