apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdx1-qa-syslog
  namespace: argocd
  labels:
    environment: qa
    component: logging
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: noctel-syslog/charts
    helm:
      valueFiles:
      - ../environments/pdx1-qa-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
