global:
  namespace: dev
  imagePullSecrets:
    - name: harbor-pull
    - name: dockerhub-secret

noctel-api-platform-sync:
  enabled: true
  replicaCount: 1
  extraEnv:
    - name: PLATFORM_SYNC_ENV
      value: "dev"
