apiVersion: v1
kind: ConfigMap
metadata:
  name: chirpstack-mosquitto-config
  namespace: qa
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    log_dest stdout
    log_type error
    connection_messages true
    log_timestamp true