global:
  namespace: qa

chirpstack-mosquitto:
    version: "2.0.18"
    image:
      pullPolicy: IfNotPresent
    replicaCount: 2
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
