chirpstack-mosquitto:
    version: "latest"
    replicaCount: 3
    image:
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
    securityContext:
      runAsUser: 1883
      runAsGroup: 1883
      runAsNonRoot: true
      fsGroup: 1883
