global:
  cluster: pdx1
  namespace: dev
  domain:
    prefix: pdx1-dev
    base: telnoc.com

noctel-notify-slack-out:
  version: "latest"
  replicaCount: 1
  image:
    pullPolicy: Always
  env:
    HEALTH_PORT: "9405"
    SERVICE_NAME: noctel-notify-slack-out
  secrets:
