apiVersion: v2
name: noctel-api-actions
description: noctel-api-actions - Standalone separated chart for individual deployment
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: NocTel Team
    email: tech@noctel.com
