{{- if and (dig "noctel-worker-fax" "metrics" "enabled" false (.Values | toJson | fromJson)) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    app.kubernetes.io/component: fax-worker
    app.kubernetes.io/instance: noctel-{{ .Values.global.namespace }}
    app.kubernetes.io/name: noctel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: fax-worker
      app.kubernetes.io/instance: noctel-{{ .Values.global.namespace }}
      app.kubernetes.io/name: noctel
  endpoints:
  - port: {{ index .Values "noctel-worker-fax" "metrics" "port" | default "http" }}
    path: {{ index .Values "noctel-worker-fax" "metrics" "path" | default "/metrics" }}
    interval: {{ index .Values "noctel-worker-fax" "metrics" "interval" | default "30s" }}
    scrapeTimeout: {{ index .Values "noctel-worker-fax" "metrics" "scrapeTimeout" | default "10s" }}
{{- end }}
