global:
  cluster: ""
  namespace: ""
  domain:
    prefix: ""
    base: ""

noctel-notify-phone-out:
  version: "latest"
  replicaCount: 1
  image:
    pullPolicy: Always
  env: {}
  secrets: {}
  resources: {}
