apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-filer
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    app: {{ .Chart.Name }}-filer
    component: filer
spec:
  clusterIP: None
  ports:
  - name: filer
    port: 8888
    targetPort: 8888
  - name: grpc
    port: 18888
    targetPort: 18888
  selector:
    app: {{ .Chart.Name }}-filer