{{- if index .Values "seaweedfs" "deployVolume" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-volume
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    app: {{ .Chart.Name }}-volume
    component: volume
spec:
  replicas: {{ index .Values "seaweedfs" "replicaCount" }}
  serviceName: {{ .Chart.Name }}-volume
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-volume
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-volume
        component: volume
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      {{- with index .Values "seaweedfs" "securityContext" }}
      securityContext:
        fsGroup: {{ .fsGroup }}
        runAsGroup: {{ .runAsGroup }}
        runAsNonRoot: {{ .runAsNonRoot }}
        runAsUser: {{ .runAsUser }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Chart.Name }}-volume
              topologyKey: kubernetes.io/hostname
      containers:
      - name: {{ .Chart.Name }}-volume
        image: "{{ index .Values "seaweedfs" "image" "repository" }}:{{ index .Values "seaweedfs" "version" }}"
        imagePullPolicy: {{ index .Values "seaweedfs" "image" "pullPolicy" }}
        command:
        - /usr/bin/weed
        args:
        - volume
        - -mserver={{ .Chart.Name }}-master-client.{{ .Values.global.namespace }}.svc.cluster.local:9333
        - -ip=$(POD_NAME).{{ .Chart.Name }}-volume.{{ .Values.global.namespace }}.svc.cluster.local
        - -port=8080
        - -dir=/data
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8080
          name: volume
        - containerPort: 18080
          name: grpc
        {{- with index .Values "seaweedfs" "resources" }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with index .Values "seaweedfs" "securityContext" }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: {{ .runAsUser }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: volume-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: volume-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ index .Values "seaweedfs" "persistence" "storageClass" }}
      resources:
        requests:
          storage: {{ index .Values "seaweedfs" "persistence" "size" }}
{{- end }}