{{- if index .Values .Chart.Name "secrets" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.global.namespace | default "default" }}
type: Opaque
stringData:
  {{- range $key, $value := index .Values .Chart.Name "secrets" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
