global:
  namespace: dev

chirpstack-gateway-bridge:
    version: "4.0.9"
    replicaCount: 3
    image:
      pullPolicy: IfNotPresent
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
    env:
      RUST_LOG: info
    config:
      mqtt:
        server: "tcp://chirpstack-mosquitto:1883"
