apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noctel-api-storage-qa
  namespace: argocd
  labels:
    environment: qa
    component: noctel-api-storage
spec:
  project: noctel-qa
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: noctel-api-storage/charts
    helm:
      valueFiles:
        - ../environments/pdx2-qa-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
