global:
  cluster: pdx1
  namespace: qa
  domain:
    prefix: pdx1-qa
    base: telnoc.com

noctel-api-storage:
  version: "latest"
  replicaCount: 1
  env:
    STORAGE_KEY_2: "2:d85e13c6b81c5fc067e1968d112a44a3cc331f1d1dda2e0d3e84b153019a7f81"
