global:
  cluster: pdx1
  namespace: prod
  domain:
    prefix: pdx1-prod
    base: noctel.com

noctel-api-talk:
  version: "latest"
  replicaCount: 1
  image:
    pullPolicy: Always
  env:
    SERVICE_NAME: talk
  secrets:
