apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.global.namespace | default "default" }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    log_dest stdout
    log_type error
    connection_messages true
    log_timestamp true
