apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: api-http
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: api-https
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: dashboard
  selector:
    app: {{ .Chart.Name }}
