global:
  cluster: pdx1
  namespace: qa
  domain: { prefix: pdx1-qa, base: telnoc.com }

noctel-api-fma:
  version: "latest"
  replicaCount: 2
  image: { pullPolicy: Always }
  env:
    PORT: "7082"
    HEALTH_PORT: "9082"
    HOST: "0.0.0.0"
    SERVICE_NAME: api-fma
    LOG_LEVEL: info
    NODE_ENV: qa
  resources:
    requests: { cpu: 100m, memory: 192Mi }
    limits:   { cpu: "1", memory: 768Mi }
