apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chirpstack-mosquitto-dev
  namespace: argocd
  labels:
    environment: dev
    component: chirpstack-mosquitto
spec:
  project: noctel-dev
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: charts/chirpstack-mosquitto
    helm:
      valueFiles:
        - ../../environments/pdx2/pdx2-dev-config.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true