apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nt-mq-mailer-qa
  namespace: argocd
  labels:
    environment: qa
    component: nt-mq-mailer
spec:
  project: noctel-qa
  source:
    repoURL: git@bitbucket.org:noctel-bitbucket/noctel-gitops.git
    targetRevision: HEAD
    path: manifests/nt-mq-mailer
    helm:
      valueFiles:
        - ../../environments/qa-config.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
