apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-{{ .Release.Namespace }}
  labels:
    app: traefik-{{ .Release.Namespace }}
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-{{ .Release.Namespace }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: traefik.io/ingress-controller
