apiVersion: v1
data:
  api-key: YjJmNGU4ZDMtM2E3Yy00ZjViLTllMWEtOGM3ZDZiNWE0ZjNl
  api-secret: ZDdlOGY5YTAtMWIyYy0zZDRlLTVmNmEtN2I4YzlkMGUxZjJh
  email: bm9jQHRlbG5vYy5jb20=
kind: Secret
metadata:
  name: dnsmadeeasy-credentials
  namespace: qa
type: Opaque
