apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: noctel-qa
    meta.helm.sh/release-namespace: qa
    metallb.universe.tf/ip-allocated-from-pool: qa-vlan-pool
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: noctel-qa
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: noctel-now
    app.kubernetes.io/part-of: noctel-now
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: noctel-now-0.1.0
  name: noctel-qa-ui-lb
  namespace: qa
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.0.98.28
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/instance: traefik-qa-qa
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer