apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-qa
  namespace: qa
  labels:
    app.kubernetes.io/instance: traefik-qa-qa
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-37.0.0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem