apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ index .Values "noctel-api-chirp-in" "version" }}
spec:
  replicas: {{ index .Values "noctel-api-chirp-in" "replicaCount" }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: noctel
        version: {{ index .Values "noctel-api-chirp-in" "version" }}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - noctel
              topologyKey: kubernetes.io/hostname

      imagePullSecrets:
      - name: harbor-pull
      - name: dockerhub-secret
      containers:
      - name: {{ .Chart.Name }}
        image: "pdx-harbor.telnoc.com/noctel/{{ .Chart.Name }}:{{ index .Values "noctel-api-chirp-in" "version" }}"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        envFrom:
          - configMapRef:
              name: noctel-platform-env
          - secretRef:
              name: noctel-api-secrets
        env:
        {{- range $key, $value := index .Values "noctel-api-chirp-in" "env" }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := index .Values "noctel-api-chirp-in" "secrets" }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
