apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: monitoring
  labels:
    release: kube-prometheus-stack-pdx1
    component: rabbitmq
spec:
  namespaceSelector:
    matchNames:
      - prod
      - qa
      - dev
  selector:
    matchLabels:
      app.kubernetes.io/name: ha-rabbit
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
